# Generated by Django 4.2 on 2023-04-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_title_productvariant_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
